language: android
dist: trusty
before_install:
  - chmod +x gradlew
  -  yes | sdkmanager "platforms;android-30"
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project


    # The SDK version used to compile your project
    - android-30


    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86_64-google_apis-android-30
before_script:
      - echo no | android create avd --force -n test -t android-30 --abi sys-img-x86_64 --tag google_apis-android-30
      - android list targets
      - emulator -avd test -no-skin -no-audio -no-window &
      - android-wait-for-emulator
      - adb shell input keyevent 82 &

